### ISSUE TITLE
Arquitectura de desarollo

### ISSUE THREAD

**Issue by nrdino** [SLAYER-CODE/Fask#1]
Como hacer una arquitectura de desarollo?

**Comment by SLAYER-CODE** [comment]
Facil podemos implementar una arquitectura llamada MVVM o MVC dependiendo de los requerimientos solicitados

**Comment by SLAYER-CODE** [comment]
Arquitectura definida como MVC para EL MODELO LA VISTA Y EL CONTROLADOR DE LAS 2 PARTES
